spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Welcome!01
    url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/
    username: admin_hosp_mgnmt
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: thwpfmkwoupfvwfx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: motivityhospital@gmail.com
    

jwt:
  secret: screatKey123
#  for frontend domain
domain:
  name: http://frontend-service.default.svc.cluster.local:3000/
